# Using official ubuntu image as a parent image
FROM ubuntu:latest

# Setting the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY scripts/airflow/start_webserver_scheduler.sh /app/

# Getting the updates for Ubuntu
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y 
RUN apt-get install -y apt-utils
RUN apt-get install -y sudo 
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y iproute2
RUN apt-get install -y mysql-client
RUN apt-get install -y python3.8
RUN apt-get install -y python3-pip
RUN apt-get install -y libmysqlclient-dev

# install airflow
RUN chmod 777 -R /opt
ENV AIRFLOW_HOME=/opt/airflow
RUN pip install mysql-connector-python
RUN pip install -U apache-airflow-providers-mysql
RUN pip install "apache-airflow==2.0.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.0.2/constraints-3.8.txt"

# add a non-root user 'bootcamp'
RUN useradd -rm -d /home/bootcamp -s /bin/bash -g root -G sudo -u 1001 bootcamp
RUN echo 'bootcamp:bootcamp' | chpasswd
USER bootcamp
WORKDIR /home/bootcamp
RUN echo "alias python=python3.8" >> /home/bootcamp/.bashrc

# airflow setup
RUN airflow db init
RUN airflow users create -u admin -p admin -f boot -l camp -r Admin -e jianrong.mo@capgemini.com
