version: '2.2'
services:
#  restapi:
#    build: 
#      context: .
#      dockerfile: Dockerfile_RestAPI.txt
#    ports:
#      - '5000:5000'
#    volumes:
#      - .:/code
#    environment:
#      FLASK_ENV: development
#    container_name: bootcamp_restapi
#  mysql:
#    image: 'brianjrmo/bootcamp:mysql'
#    container_name: bootcamp_mysql
  scheduler:
    image: 'brianjrmo/bootcamp:airflow'
    container_name: bootcamp_airflow_scheduler
    restart: always
    entrypoint: airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
  webserver:
    image: 'brianjrmo/bootcamp:airflow'
    container_name: bootcamp_airflow_webserver
    restart: always
    entrypoint: airflow webserver
    depends_on:
      - scheduler
    ports:
      - '8080:8080'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts


