version: '2.2'
services:
  restapi:
    build: 
      context: .
      dockerfile: Dockerfile_RestAPI.txt
    ports:
      - '5000:5000'
    volumes:
      - ./scripts/restapi:/code
    environment:
      FLASK_ENV: development
    container_name: bootcamp_restapi
  mysql:
#    image: 'brianjrmo/bootcamp:mysql'
    image: 'mysql/mysql-server:latest'
    container_name: bootcamp_mysql
    depends_on:
      - restapi
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "bootcamp"
      MYSQL_USER: "bootcamp"
      MYSQL_PASSWORD: "bootcamp"
      MYSQL_DATABASE: "mysql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
  airflow:
    image: 'brianjrmo/bootcamp:airflow'
    container_name: bootcamp_airflow
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - '8080:8080'
    entrypoint: sh -x /app/start_webserver_scheduler.sh
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs